### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xplsql#2]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

------

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by chezwicker** [comment]
I've added the requested comments to the _SETUP.md_ file.

Unfortunately, testing this showed that the content was not included in _README.md_ (deleted existing files and ran `exercism fetch`).

**Comment by kytrinyx** [comment]
This is working for me. Steps to confirm:

1. Delete my `hamming` problem for this track.
2. Run `exercism fetch`
3. Open README.md; it has the _setup_ contents right before the source.

I also got it if I fetched a particular problem, e.g. `exercism fetch plsql raindrops`.

**Comment by chezwicker** [comment]
Ah, works now - strange. When I first tried the above steps, only the _Setup_ section was included. No idea why and how. Closing this issue, then.
